export default interface NutritionDiaryProps {
    _id: string,
    meal?: number,
    product_ID?: string,
    how_many?: number,
    name?: string,
    l?: number,
    v?: boolean,
    deleted?: boolean,
    user_ID?: string,
    checkMe?: boolean,
    code?: number,
    p?: number,
    c?: number,
    s?: number,
    f?: number,
    fi?: number,
    na?: number,
    ethanol?: number,
    activity?: string,
    calories?: number
}